#!/bin/bash

git diff --quiet HEAD
# if [ "$?" -ne "0" ]; then
#    echo "Local repo is not clean!"
#    exit 1
# fi

set -ex

rm -rf lib
yarn tsc

sudo docker build . -f Dockerfile -t registry-intl.ap-southeast-1.aliyuncs.com/one_subscribe/subscribe:$1
sudo docker push registry-intl.ap-southeast-1.aliyuncs.com/one_subscribe/subscribe:$1

git tag -a $1 -m "$1"
git push origin $1